
import { Technique, Student } from './types';

const createBeltTechs = (belt: any, prefix: string, names: { name: string, cat: any, desc: string }[]): Technique[] => {
  return names.map((t, i) => ({
    id: `${prefix}-${i + 1}`,
    name: t.name,
    category: t.cat,
    beltRequired: belt,
    description: t.desc
  }));
};

export const INITIAL_TECHNIQUES: Technique[] = [
  // --- FAIXA BRANCA (30 TÉCNICAS) ---
  ...createBeltTechs('Branca', 'w', [
    { name: 'Rolamento de Frente', cat: 'Fundamentos', desc: 'Base para quedas e segurança no tatame.' },
    { name: 'Fuga de Quadril Lateral', cat: 'Fundamentos', desc: 'Movimento essencial para reposição de guarda.' },
    { name: 'Upa (Ponte)', cat: 'Fundamentos', desc: 'Explosão de quadril para desequilibrar quem está montado.' },
    { name: 'Postura na Guarda Fechada', cat: 'Fundamentos', desc: 'Prevenção de ataques mantendo o alinhamento da coluna.' },
    { name: 'Escapada da Montada (Upa)', cat: 'Fundamentos', desc: 'Saída clássica utilizando a ponte e o bloqueio de braço.' },
    { name: 'Escapada da Montada (Cotovelo/Joelho)', cat: 'Fundamentos', desc: 'Recuperação de meia guarda ou guarda fechada.' },
    { name: 'Saída do Lado (Barrigada/Reposição)', cat: 'Fundamentos', desc: 'Uso do quadril para criar espaço e repor a guarda.' },
    { name: 'Quebra de Guarda Fechada de Joelhos', cat: 'Passagem', desc: 'Abertura de guarda controlando o quadril do oponente.' },
    { name: 'Quebra de Guarda Fechada em Pé', cat: 'Passagem', desc: 'Uso da gravidade e postura para romper o cadeado.' },
    { name: 'Passagem Toureando (Básica)', cat: 'Passagem', desc: 'Passagem de velocidade controlando as calças.' },
    { name: 'Passagem de Joelho Cruzado', cat: 'Passagem', desc: 'Slide de joelho para vencer a meia guarda.' },
    { name: 'Passagem de Meia Guarda (Tripé)', cat: 'Passagem', desc: 'Pressão de ombro no rosto e livrar a perna presa.' },
    { name: 'Raspagem de Tesoura', cat: 'Guarda', desc: 'Uso das canelas para tesourar as pernas do oponente.' },
    { name: 'Raspagem de Quadril (Hip Bump)', cat: 'Guarda', desc: 'Aproveitar a postura baixa para sentar e raspar.' },
    { name: 'Raspagem Pendular', cat: 'Guarda', desc: 'Uso do peso da perna externa para girar o oponente.' },
    { name: 'Armlock da Guarda Fechada', cat: 'Finalização', desc: 'Chave de braço clássica com giro de 90 graus.' },
    { name: 'Triângulo da Guarda Fechada', cat: 'Finalização', desc: 'Estrangulamento com as pernas isolando o braço.' },
    { name: 'Kimura da Guarda Fechada', cat: 'Finalização', desc: 'Ataque de ombro em duas direções.' },
    { name: 'Guilhotina', cat: 'Finalização', desc: 'Estrangulamento frontal aproveitando o pescoço exposto.' },
    { name: 'Americana da Montada', cat: 'Finalização', desc: 'Chave de ombro clássica por cima.' },
    { name: 'Ezequiel da Montada', cat: 'Finalização', desc: 'Estrangulamento usando a própria manga.' },
    { name: 'Mata Leão', cat: 'Finalização', desc: 'O "Rei das Finalizações" aplicado pelas costas.' },
    { name: 'Estrangulamento Cruzado (Montada)', cat: 'Finalização', desc: 'Uso das quatro pontas de dedos dentro da gola.' },
    { name: 'Double Leg (Baiana)', cat: 'Quedas', desc: 'Derrubada controlando as duas pernas.' },
    { name: 'Single Leg Básico', cat: 'Quedas', desc: 'Derrubada controlando uma perna.' },
    { name: 'Osoto Gari', cat: 'Quedas', desc: 'Projeção de judô com gancho por fora.' },
    { name: 'Defesa de Gravata de Porteiro', cat: 'Defesa Pessoal', desc: 'Saída de agarre lateral de pescoço.' },
    { name: 'Defesa de Empurrão no Peito', cat: 'Defesa Pessoal', desc: 'Controle de distância e desvio de força.' },
    { name: 'Defesa de Chute Frontal', cat: 'Defesa Pessoal', desc: 'Bloqueio e aproximação para clinch.' },
    { name: 'Sprawl (Defesa de Queda)', cat: 'Fundamentos', desc: 'Atirar as pernas para trás para defender double leg.' },
  ]),

  // --- FAIXA AZUL (30 TÉCNICAS) ---
  ...createBeltTechs('Azul', 'b', [
    { name: 'Omoplata da Guarda', cat: 'Finalização', desc: 'Ataque de ombro com as pernas em transição.' },
    { name: 'Triângulo de Mão (Darce)', cat: 'Finalização', desc: 'Estrangulamento de braço e cabeça lateral.' },
    { name: 'Mata Leão de Pé (Bow and Arrow)', cat: 'Finalização', desc: 'Uso da calça e gola para máxima alavanca.' },
    { name: 'Relógio (Clock Choke)', cat: 'Finalização', desc: 'Estrangulamento na tartaruga caminhando em círculo.' },
    { name: 'Guarda De La Riva (Básico)', cat: 'Guarda', desc: 'Uso do gancho externo para controle de distância.' },
    { name: 'Guarda Lasso (Laço)', cat: 'Guarda', desc: 'Controle de manga com a perna laçada.' },
    { name: 'Guarda X (Entrada Básica)', cat: 'Guarda', desc: 'Posicionamento sob o centro de gravidade do oponente.' },
    { name: 'Raspagem de Gancho (Butterfly)', cat: 'Guarda', desc: 'Uso do peito do pé para elevar o quadril adversário.' },
    { name: 'Raspagem de Omoplata', cat: 'Guarda', desc: 'Finalização que vira raspagem quando o oponente rola.' },
    { name: 'Raspagem De La Riva (Sit Up)', cat: 'Guarda', desc: 'Sentar para abraçar a perna e raspar de single leg.' },
    { name: 'Passagem de Emborrachada', cat: 'Passagem', desc: 'Uso das duas mãos por baixo das pernas (Double Under).' },
    { name: 'Passagem Leg Drag (Básico)', cat: 'Passagem', desc: 'Cruzar a perna do oponente para isolar o quadril.' },
    { name: 'Passagem de Pressão (Over-Under)', cat: 'Passagem', desc: 'Uma mão por cima e outra por baixo da perna.' },
    { name: 'Escape de Triângulo', cat: 'Fundamentos', desc: 'Postura e quebra de cadeado de pernas.' },
    { name: 'Escape de Armlock (Hitchhiker)', cat: 'Fundamentos', desc: 'Giro de polegar para fora para escapar da chave.' },
    { name: 'Defesa de Omoplata (Cambalhota)', cat: 'Fundamentos', desc: 'Rolar sobre o ombro antes do ajuste final.' },
    { name: 'North-South Choke', cat: 'Finalização', desc: 'Estrangulamento na posição de 100 quilos invertida.' },
    { name: 'Americana de Pé (Wrist Lock)', cat: 'Finalização', desc: 'Chave de pulso (permitida a partir da azul).' },
    { name: 'Ankle Lock (Reta)', cat: 'Finalização', desc: 'Chave de calcanhar reta/pé.' },
    { name: 'Katagatame', cat: 'Finalização', desc: 'Estrangulamento de triângulo de braço por cima.' },
    { name: 'Ouchi Gari', cat: 'Quedas', desc: 'Gancho por dentro no calcanhar.' },
    { name: 'Seoi Nage', cat: 'Quedas', desc: 'Projeção sobre o ombro.' },
    { name: 'Tomoe Nage', cat: 'Quedas', desc: 'Raspagem de balão usando o pé no abdômen.' },
    { name: 'Defesa de Guilhotina em Pé', cat: 'Defesa Pessoal', desc: 'Postura e projeção para defesa de pescoço.' },
    { name: 'Defesa de Abraço de Urso', cat: 'Defesa Pessoal', desc: 'Uso da base para não ser levantado.' },
    { name: 'Abraço pelas Costas (Saída)', cat: 'Defesa Pessoal', desc: 'Deslizar o quadril para o lado e girar.' },
    { name: 'Kimura Trap System', cat: 'Transições', desc: 'Uso do grip de kimura para controlar o corpo todo.' },
    { name: 'Berimbolo (Iniciação)', cat: 'Guarda', desc: 'Giro para as costas a partir da De La Riva.' },
    { name: 'Guarda Aranha (Spider)', cat: 'Guarda', desc: 'Controle de braços usando os pés nos bíceps.' },
    { name: 'Snapdown para Sprawl', cat: 'Quedas', desc: 'Puxar a cabeça para baixo e atacar as costas.' },
  ]),

  // --- FAIXA ROXA (30 TÉCNICAS) ---
  ...createBeltTechs('Roxa', 'p', [
    { name: 'Berimbolo Avançado', cat: 'Guarda', desc: 'Encadeamento de giros para controle total das costas.' },
    { name: 'Guarda Worm (Verme)', cat: 'Guarda', desc: 'Uso da lapela por baixo da perna para controle absoluto.' },
    { name: 'Guarda de Lapela (Squid)', cat: 'Guarda', desc: 'Variação de lapela para raspagens de força.' },
    { name: 'Triângulo de Mão (Anaconda)', cat: 'Finalização', desc: 'Giro por baixo para finalizar no pescoço.' },
    { name: 'Brabo Choke (Lapela)', cat: 'Finalização', desc: 'Uso da lapela do oponente para estrangular no cem quilos.' },
    { name: 'Rolling Back Take', cat: 'Guarda', desc: 'Pulo para as costas quando o oponente tenta passar.' },
    { name: 'Estima Lock', cat: 'Finalização', desc: 'Chave de pé surpresa atacando o dorso.' },
    { name: 'Calf Slicer (Esmaga Panturrilha)', cat: 'Finalização', desc: 'Compressão muscular permitida na roxa.' },
    { name: 'Bicep Slicer (Esmaga Bíceps)', cat: 'Finalização', desc: 'Compressão no braço via triângulo ou guarda.' },
    { name: 'Inverted Guard (Guarda Invertida)', cat: 'Guarda', desc: 'Proteção de passagem usando o corpo de cabeça para baixo.' },
    { name: 'Raspagem Kiss of the Dragon', cat: 'Guarda', desc: 'Inversão sob o quadril na guarda De La Riva invertida.' },
    { name: 'Passagem Long Step', cat: 'Passagem', desc: 'Passo longo lateral para vencer guardas abertas.' },
    { name: 'Passagem Smash Pass', cat: 'Passagem', desc: 'Dobrar as pernas do oponente sobre o próprio quadril.' },
    { name: 'Passagem de X-Pass', cat: 'Passagem', desc: 'Chute da perna para trás criando o desenho de um X.' },
    { name: 'Transição da Tartaruga para Costas', cat: 'Finalização', desc: 'Abertura de ganchos em oponentes fechados.' },
    { name: 'Baseball Bat Choke (Cem Quilos)', cat: 'Finalização', desc: 'Deixar o oponente repor a guarda para finalizar.' },
    { name: 'Crucifixo', cat: 'Finalização', desc: 'Isolamento dos dois braços do oponente pelas costas.' },
    { name: 'Ataque de Costas via Kimura', cat: 'Transições', desc: 'Sentar no quadril para girar para as costas.' },
    { name: 'Guarda 50/50 (Raspagens)', cat: 'Guarda', desc: 'Luta de posições espelhadas de perna.' },
    { name: 'Deep Half Guard (Meia Profunda)', cat: 'Guarda', desc: 'Entrar totalmente sob o quadril do passador.' },
    { name: 'Single Leg X (Entrada)', cat: 'Guarda', desc: 'Variação de guarda X controlando apenas uma perna.' },
    { name: 'Uchi Mata', cat: 'Quedas', desc: 'Projeção com levantamento de perna interna.' },
    { name: 'Sumi Gaeshi', cat: 'Quedas', desc: 'Sacrifício frontal para projeção.' },
    { name: 'Ankle Pick (Catada de Calcanhar)', cat: 'Quedas', desc: 'Baixar o nível rapidamente para pegar o pé.' },
    { name: 'Defesa de Faca (Cortes)', cat: 'Defesa Pessoal', desc: 'Controle de braço armado e desvio.' },
    { name: 'Defesa de Soco (Distância)', cat: 'Defesa Pessoal', desc: 'Clinch seguro antes do golpe atingir.' },
    { name: 'Finalização de Triângulo Invertido', cat: 'Finalização', desc: 'Ataque quando o oponente tenta passar a guarda.' },
    { name: 'Estrangulamento de Gola das Costas (Lapela)', cat: 'Finalização', desc: 'Variações de arco e flecha.' },
    { name: 'Raspagem de Balão da Meia Guarda', cat: 'Guarda', desc: 'Elevação usando o gancho de baixo.' },
    { name: 'Contra-Ataque de Single Leg (Kimura)', cat: 'Quedas', desc: 'Atacar o braço de quem tenta a queda.' },
  ]),

  // --- FAIXA MARROM (30 TÉCNICAS) ---
  ...createBeltTechs('Marrom', 'br', [
    { name: 'Kneebar (Chave de Joelho)', cat: 'Finalização', desc: 'Extensão de perna permitida na marrom.' },
    { name: 'Toe Hold (Mata Leão de Pé)', cat: 'Finalização', desc: 'Chave de torção de pé permitida na marrom.' },
    { name: 'Heel Hook Defense (Sambo Style)', cat: 'Fundamentos', desc: 'Escape e contra-ataque de calcanhar.' },
    { name: 'Pressure Passing (Peso Morto)', cat: 'Passagem', desc: 'Uso da gravidade para vencer guardas ultra-flexíveis.' },
    { name: 'Guarda Matrix', cat: 'Guarda', desc: 'Entrada para o calcanhar e costas via K-Guard.' },
    { name: 'K-Guard System', cat: 'Guarda', desc: 'Uso do joelho em K para ataques de perna e raspagens.' },
    { name: 'Dela Riva Invertida Avançada', cat: 'Guarda', desc: 'Uso de ganchos internos para evitar pressões.' },
    { name: 'Passagem de Flutuação (Float)', cat: 'Passagem', desc: 'Equilíbrio sobre as canelas do oponente.' },
    { name: 'Passagem de Meia Guarda Z', cat: 'Passagem', desc: 'Vencer o escudo de joelho com pressão de quadril.' },
    { name: 'Ataques de Pé em Cadeia', cat: 'Finalização', desc: 'Transição entre Ankle Lock e Toe Hold.' },
    { name: 'Escapadas de Meia Guarda Profunda', cat: 'Fundamentos', desc: 'Controle de base para não ser elevado.' },
    { name: 'Finalização Gogo Plata', cat: 'Finalização', desc: 'Estrangulamento com a canela no pescoço.' },
    { name: 'Triângulo de Mão das Costas', cat: 'Finalização', desc: 'Uso do braço preso para finalizar.' },
    { name: 'Chave de Ombro Invertida', cat: 'Finalização', desc: 'Variação de Kimura com pegada de braço reto.' },
    { name: 'Raspagem de Perna Cruzada (X-Guard)', cat: 'Guarda', desc: 'Uso de alavanca dupla no fêmur.' },
    { name: 'Passagem de Guarda Sanfona', cat: 'Passagem', desc: 'Aproximação de joelhos para fechar o espaço.' },
    { name: 'Contra-Ataque de Berimbolo', cat: 'Fundamentos', desc: 'Uso da perna livre para bloquear o giro.' },
    { name: 'Chave de Bíceps da Tartaruga', cat: 'Finalização', desc: 'Uso da perna para comprimir o braço.' },
    { name: 'Sode Guruma Jime (Ezequiel de Kimono)', cat: 'Finalização', desc: 'Uso das duas mangas em profundidade.' },
    { name: 'Defesa de Bastão (Longa)', cat: 'Defesa Pessoal', desc: 'Entrada no tempo do golpe.' },
    { name: 'Imobilização Policial', cat: 'Defesa Pessoal', desc: 'Uso do jiu-jitsu para contenção sem dano.' },
    { name: 'Kata Guruma (Bombeiro)', cat: 'Quedas', desc: 'Projeção sobre os ombros com joelho no chão.' },
    { name: 'De Ashi Barai', cat: 'Quedas', desc: 'Varredura de pé no tempo do passo.' },
    { name: 'Single Leg High Amplitude', cat: 'Quedas', desc: 'Levantar a perna acima do ombro para queda.' },
    { name: 'Raspagem Waite (Deep Half)', cat: 'Guarda', desc: 'Elevação e transição para o topo.' },
    { name: 'Passagem de Guarda de Borboleta (Wedge)', cat: 'Passagem', desc: 'Uso do joelho como cunha.' },
    { name: 'Ataque de Ombro (Plata)', cat: 'Finalização', desc: 'Sistemas de ataques de ombro interligados.' },
    { name: 'Controle de Montada S-Mount', cat: 'Fundamentos', desc: 'Postura em S para isolar braços.' },
    { name: 'Escape de Norte-Sul Avançado', cat: 'Fundamentos', desc: 'Uso do braço como frame e pêndulo.' },
    { name: 'Combinação Armlock/Triângulo/Omoplata', cat: 'Finalização', desc: 'O fluxo perfeito de ataques da guarda.' },
  ]),

  // --- FAIXA PRETA (30 TÉCNICAS) ---
  ...createBeltTechs('Preta', 'bl', [
    { name: 'O Jiu-Jitsu Invisível (Conceito)', cat: 'Fundamentos', desc: 'Distribuição de peso e alavancas milimétricas.' },
    { name: 'Pressão de Ombro (Cross Face)', cat: 'Fundamentos', desc: 'Otimização do torque no pescoço adversário.' },
    { name: 'Gestão de Energia (Eficiência)', cat: 'Fundamentos', desc: 'Lutar sem força usando apenas estrutura óssea.' },
    { name: 'Conexão de Sistema de Ataques', cat: 'Finalização', desc: 'Previsão de reações para antecipar finalizações.' },
    { name: 'Contra-Ataque de Leg Drag', cat: 'Guarda', desc: 'Uso da inércia para repor e atacar.' },
    { name: 'Guarda de Lapela (Master System)', cat: 'Guarda', desc: 'Uso criativo do kimono para amarrar o jogo.' },
    { name: 'Raspagem de Gancho Invertido', cat: 'Guarda', desc: 'Uso de ganchos em ângulos não convencionais.' },
    { name: 'Passagem de Guarda em Pé (Sustentação)', cat: 'Passagem', desc: 'Postura inabalável contra guardeiros.' },
    { name: 'Passagem sem Mãos (No Hands)', cat: 'Passagem', desc: 'Uso exclusivo de equilíbrio e quadril.' },
    { name: 'Finalizações de Pulso (Especialista)', cat: 'Finalização', desc: 'Mão de vaca em todas as posições.' },
    { name: 'Estrangulamentos de Gola Curta', cat: 'Finalização', desc: 'Finalização sem necessidade de ganchos fundos.' },
    { name: 'Cem Quilos para Montada (Fluidez)', cat: 'Fundamentos', desc: 'Transição sem dar espaço de reposição.' },
    { name: 'Defesa de Chave de Pé (Prevenção)', cat: 'Fundamentos', desc: 'Esconder o calcanhar antes do ataque ocorrer.' },
    { name: 'Raspagem de Gancho Profundo', cat: 'Guarda', desc: 'Desequilíbrio de micro-movimento.' },
    { name: 'Escape de Costas (Giro de Ombro)', cat: 'Fundamentos', desc: 'Prevenção de ganchos e limpeza de golas.' },
    { name: 'Ataque de Braço da Tartaruga (Giro)', cat: 'Finalização', desc: 'Salto para armlock em oponente fechado.' },
    { name: 'Triângulo Lateral (Side Triangle)', cat: 'Finalização', desc: 'Ataque a partir do controle lateral.' },
    { name: 'Kimura de Norte-Sul (Variação)', cat: 'Finalização', desc: 'Alavanca máxima com uso do tronco.' },
    { name: 'Escape de Armlock (Stack Pass)', cat: 'Fundamentos', desc: 'Transformar a defesa em passagem de guarda.' },
    { name: 'Defesa de Arma de Fogo', cat: 'Defesa Pessoal', desc: 'Desvio de cano e desarme à curta distância.' },
    { name: 'Combate em Ambiente Fechado', cat: 'Defesa Pessoal', desc: 'Uso do jiu-jitsu em espaços restritos.' },
    { name: 'Tani Otoshi (Queda de Sacrifício)', cat: 'Quedas', desc: 'Derrubada lateral segura.' },
    { name: 'Ippon Seoi Nage (Avançado)', cat: 'Quedas', desc: 'Entrada com braço totalmente isolado.' },
    { name: 'Ko Uchi Gari para Double Leg', cat: 'Quedas', desc: 'Combinação de judô e wrestling.' },
    { name: 'Raspagem Estrela (Star Sweep)', cat: 'Guarda', desc: 'Giro completo sobre os ombros.' },
    { name: 'Passagem de Meia Guarda Invertida', cat: 'Passagem', desc: 'Uso do pé livre para empurrar o joelho.' },
    { name: 'Chave de Perna 411 (Honey Hole)', cat: 'Finalização', desc: 'Controle sistêmico de pernas.' },
    { name: 'Estrangulamento Loop Choke', cat: 'Finalização', desc: 'Surpresa de gola em transição de entrada.' },
    { name: 'Defesa de Estrangulamento pelas Costas', cat: 'Fundamentos', desc: 'Luta de mãos e queixo.' },
    { name: 'O Fluxo do Mestre (Randori)', cat: 'Fundamentos', desc: 'Adaptação contínua ao movimento do outro.' },
  ]),
];

const currentMonth = new Date().toISOString().slice(0, 7);

export const MOCK_STUDENTS: Student[] = [
  {
    id: 's1',
    name: 'Carlos Gracie Jr',
    email: 'carlos@bjj.com',
    password: '123',
    age: 28,
    weight: 78,
    category: 'Adulto',
    currentBelt: 'Azul',
    currentStripes: 2,
    joinedDate: '2023-01-15',
    attendanceHistory: ['2024-05-01', '2024-05-03', '2024-05-05', '2024-05-10', '2024-05-12'],
    masteredTechniques: ['w-1', 'w-2', 'w-3', 'w-10', 'w-16', 'b-1', 'b-5'],
    role: 'student',
    photoUrl: 'https://picsum.photos/seed/carlos/200',
    academyName: 'Gracie Barra Headquarters',
    monthlyTuition: 150,
    payments: [currentMonth],
    planType: 'Mensal'
  },
  {
    id: 's2',
    name: 'Helio Professor',
    email: 'admin@bjj.com',
    password: 'admin',
    age: 45,
    weight: 82,
    category: 'Adulto',
    currentBelt: 'Preta',
    currentStripes: 4,
    joinedDate: '2010-01-01',
    attendanceHistory: [],
    masteredTechniques: INITIAL_TECHNIQUES.map(t => t.id),
    role: 'admin',
    photoUrl: 'https://picsum.photos/seed/helio/200',
    academyName: 'Gracie Barra Headquarters',
    monthlyTuition: 0,
    payments: [],
    planType: 'Mensal'
  }
];

export const BELT_COLORS_HEX: Record<string, string> = {
  'Branca': '#FFFFFF',
  'Cinza e Branca': '#d1d5db',
  'Cinza': '#9ca3af',
  'Cinza e Preta': '#4b5563',
  'Amarela e Branca': '#fef08a',
  'Amarela': '#fbbf24',
  'Amarela e Preta': '#d97706',
  'Laranja e Branca': '#fdba74',
  'Laranja': '#f97316',
  'Laranja e Preta': '#c2410c',
  'Verde e Branca': '#86efac',
  'Verde': '#22c55e',
  'Verde e Preta': '#15803d',
  'Azul': '#2563eb',
  'Roxa': '#7c3aed',
  'Marrom': '#78350f',
  'Preta': '#000000',
  'Vermelha e Preta': '#b91c1c',
  'Vermelha e Branca': '#ef4444',
  'Vermelha': '#dc2626',
};

export const BELT_TEXT_COLORS_HEX: Record<string, string> = {
  'Branca': '#1f2937',
  'Cinza e Branca': '#1f2937',
  'Cinza': '#FFFFFF',
  'Cinza e Preta': '#FFFFFF',
  'Amarela e Branca': '#1f2937',
  'Amarela': '#1f2937',
  'Amarela e Preta': '#FFFFFF',
  'Laranja e Branca': '#1f2937',
  'Laranja': '#FFFFFF',
  'Laranja e Preta': '#FFFFFF',
  'Verde e Branca': '#1f2937',
  'Verde': '#FFFFFF',
  'Verde e Preta': '#FFFFFF',
  'Azul': '#FFFFFF',
  'Roxa': '#FFFFFF',
  'Marrom': '#FFFFFF',
  'Preta': '#FFFFFF',
  'Vermelha e Preta': '#FFFFFF',
  'Vermelha e Branca': '#FFFFFF',
  'Vermelha': '#FFFFFF',
};
